-- ==============================================================================
-- OBSOLETO — Este script abría el acceso público (inseguro).
--
-- La configuración segura (autenticación + RLS por usuario + buckets privados)
-- está ahora en:  supabase-setup.sql
--
-- - Instalación nueva: ejecuta  supabase-setup.sql
-- - Migrar una instalación pública existente: ejecuta  migrate_to_auth.sql
-- ==============================================================================
