-- ==============================================================================
-- OBSOLETO — La configuración ahora es única y segura.
--
-- Toda la creación de tablas (incluida playlist_songs), la seguridad RLS por
-- usuario y los buckets privados están en:  supabase-setup.sql
--
-- - Instalación nueva: ejecuta  supabase-setup.sql
-- - Migrar una instalación pública existente: ejecuta  migrate_to_auth.sql
-- ==============================================================================
